### ISSUE TITLE
ML/AI Feedbacks

### ISSUE THREAD

**Issue by bhack** [canonical-debate-lab/paper#2]
It could be interesting to collect some feedbacks to this paper from @conversationai

**Comment by bigokro** [comment]
Feel free to reach out! We haven't reached the AI part of our white paper yet, but you can add some information there if you wish via a PR

**Comment by BentleyDavis** [comment]
Noted. There is an AI section in the paper and pull requested are encouraged. But phase 1 will not include any AI or ML in the application.
